# Generated by Django 2.2 on 2020-04-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autolisting',
            name='aasta',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autolisting',
            name='hind',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
