# Generated by Django 2.2 on 2020-05-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20200417_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='autolisting',
            name='url',
            field=models.TextField(default='lol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autolisting',
            name='vedu',
            field=models.TextField(default='lol'),
            preserve_default=False,
        ),
    ]
